newupdates

diff --git a/websitemanager b/websitemanager
--- a/websitemanager
+++ b/websitemanager
@@ -148,8 +148,6 @@ websitemanager-list() {
     echo-green "Virtual hosts enabled:"
     ls -1 "/etc/apache2/sites-enabled/"
 
-    exit 1
-
 }
 
 websitemanager-install() {
@@ -167,17 +165,17 @@ websitemanager-install() {
         echo "ALL ALL = NOPASSWD: /usr/bin/cat, /usr/bin/update-alternatives, /usr/bin/websitemanager, /usr/bin/systemmanager, /bin/systemctl restart apache2, /bin/kill" >> /etc/sudoers
     fi
     
-    #cd $CONFDIR
-    #git checkout .
-    #git remote update > /dev/null
-    #needUpdate=$(git status -uno | grep -c "git pull")
+    cd $CONFDIR
+    git checkout .
+    git remote update > /dev/null
+    needUpdate=$(git status -uno | grep -c "git pull")
 
-    # if [ "$needUpdate" -ne 0 ]; then
-    #     echo-yellow "there are some updates, would you like to update y/n"
-    #     read updates
-    #     if [ "$updates" = "y" ];then
-    #        git reset --hard origin/master > /dev/null
-    #        echo-green "Update complete!"
+     if [ "$needUpdate" -ne 0 ]; then
+         echo-yellow "there are some updates, would you like to update y/n"
+         read updates
+         if [ "$updates" = "y" ];then
+            git reset --hard origin/master > /dev/null
+            echo-green "Update complete!"
             if [ ! -f  "$STATUS" ];then
                 touch ${STATUS}
             fi    
@@ -186,9 +184,9 @@ websitemanager-install() {
                 echo-red "Upgrade required Please run sudo systemmanager"
                 exit 1
             fi    
-    #     fi
+         fi
        
-    # fi
+    fi
 
 }
 
@@ -279,21 +277,22 @@ websitemanager-generate-php-pool() {
 }
 
 websitemanager-remove() {
-    FPM_POOL_CONF="/etc/$PHP_VERSION/fpm/pool.d/$DOMAIN.conf"
+    FPM_POOL_CONF="/etc/php/*/fpm/pool.d/$DOMAIN.conf"
 
     echo-yellow "removing domain from /etc/hosts."
     sed -i '/'$DOMAIN'/d' /etc/hosts
+    sed -i '/'www\.$DOMAIN'/d' /etc/hosts
 
-    echo-yellow "disabling  $DOMAIN virtual host."
+    echo-yellow "Disabling  $DOMAIN virtual host."
     a2dissite $DOMAIN.conf
 
     rm "/etc/apache2/sites-available/$DOMAIN.conf"
     service apache2 reload
 
-    if [ -f "$FPM_POOL_CONF" ]; then
-        echo-yellow "removing php-fpm associaed with $DOMAIN"
-        rm "$FPM_POOL_CONF"
-    fi
+    
+    echo-red "Removing php-fpm associaed with $DOMAIN"
+    rm "$FPM_POOL_CONF"
+    
 
     exit 0
 
@@ -407,8 +406,52 @@ if [ ! "$TEMPLATE" == "node.conf" ];then
 	echo-green "sudo update-alternatives --set php /usr/bin/phpversion"
 fi
 }
-
+verifyuserinput(){
+clear    
+echo-red "=============================================================================="
+echo-green
+echo-green "Domain: $DOMAIN"
+echo-green "Vhost Template: $TEMPLATE"
+if [ ! "$TEMPLATE" == "proxy"  ]; then
+echo-green "PHP Version: $PHP_VERSION"
+HAS_POOL_TEMPLATE="1"
+DOCUMENT_ROOT=/home/$USERNAME/public_html/sites/$DOMAIN/
+echo-green "DOCUMENT_ROOT: $DOCUMENT_ROOT"
+else
+echo-green "PORT: $PORT"
+fi
+if [ -z "$FRAMEWORK"  ]; then
+echo-yellow "Framework: Not Selected"
+else
+echo-green "Install Framework: $FRAMEWORK"
+fi
+echo-green "USERNAME: $USERNAME";
+echo-green
+echo-red "=============================================================================="
+read -p "Would you like to create domain/site with above configuration (y/n)?" answer
+case ${answer:0:1} in
+    y|Y )
+        echo ""
+    ;;
+    * )
+       exit 1
+    ;;
+esac
+}
 websitemanager-install
+domain-name(){
+
+echo-yellow "Please enter the domain name:"
+    read DOMAIN
+
+    if [[ $DOMAIN =~ ^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$ ]]; then
+        echo ""
+    else
+        echo "Invalid domain name: $DOMAIN"
+        exit 1
+    fi
+
+}
 
 #=========================================================================================
 echo-yellow "Select an option"
@@ -433,18 +476,8 @@ echo-yellow "Select an option"
         esac
     done
 
-if [ ! $ACTION == "list" ]; then
-    echo-yellow "Please enter the domain name:"
-    read DOMAIN
-
-    if [[ $DOMAIN =~ ^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$ ]]; then
-        echo ""
-    else
-        echo "Invalid domain name: $DOMAIN"
-        exit 1
-    fi
-fi
-
+if [ $ACTION = "add" ]; then
+domain-name
 echo-yellow "Please select the Apache Vhost template:"
 select TEMPLATE in "default" "wordpress" "laravel" "proxy"
 do
@@ -497,61 +530,31 @@ elif [ "$FRAMEWORK_OPT" = "Yes" ] && [ "$TEMPLATE" = "laravel" ]; then
 fi
 
 
-if [ ! $TEMPLATE == "proxy" ]; then
+if [ ! $TEMPLATE = "proxy" ]; then
     PV_OPT
 else
     PORT=3000
 
 fi
 
-verifyuserinput(){
-clear    
-echo-red "=============================================================================="
-echo-green
-echo-green "Domain: $DOMAIN"
-echo-green "Vhost Template: $TEMPLATE"
-if [ ! "$TEMPLATE" == "proxy"  ]; then
-echo-green "PHP Version: $PHP_VERSION"
-HAS_POOL_TEMPLATE="1"
-DOCUMENT_ROOT=/home/$USERNAME/public_html/sites/$DOMAIN/
-echo-green "DOCUMENT_ROOT: $DOCUMENT_ROOT"
-else
-echo-green "PORT: $PORT"
-fi
-if [ -z "$FRAMEWORK"  ]; then
-echo-yellow "Framework: Not Selected"
-else
-echo-green "Install Framework: $FRAMEWORK"
-fi
-echo-green "USERNAME: $USERNAME";
-echo-green
-echo-red "=============================================================================="
-read -p "Would you like to create domain/site with above configuration (y/n)?" answer
-case ${answer:0:1} in
-    y|Y )
-        echo ""
-    ;;
-    * )
-       exit 1
-    ;;
-esac
-}
 
-#
-# Do vhost creation process
-#
-#echo-green "$HAS_POOL_TEMPLATE"
 #websitemanager-update;
-#sudoers_user;
-websitemanager-getuname;
-verifyuserinput;
+websitemanager-getuname
+verifyuserinput
 websitemanager-template;
 websitemanager-generate-vhost;
-#websitemanager-generate-php-pool;
 websitemanager-point-ip;
 websitemanager-ssl-generate;
 websitemanager-enable-reload;
-#mysqlcred;
 setupphpcli;
 install_framework;
-exit 0
+elif [ $ACTION = "list" ]; then
+     websitemanager-list
+else 
+    websitemanager-list
+    domain-name
+    websitemanager-remove
+    echo-read " DOMAIN $DOMAIN DELETED"    
+fi
+
+
